[range_estimation]
NUM_MC_RUNS = 2
NUM_RESTARTS = 20
NUM_SAMPLES = 512
NUM_TRIALS = 20
NUM_WARMUP = 10
Q = 5
ROOT = "Data"
SEED = 2009
SERIAL = "test_range_est"

[localization]
NUM_MC_RUNS = 2
NUM_RESTARTS = 40
NUM_SAMPLES = 1024
NUM_TRIALS = 20
NUM_GRID_TRIALS = [
    2,
    10,
]
NUM_WARMUP = 10
Q = 5
ROOT = "Data"
SEED = 2009
SERIAL = "test_localization"
