[range_estimation.simulation]
num_mc_runs = 100
num_restarts = 20
num_samples = 512
num_trials = 200
num_warmup = 10
q = 5
root = "Data"
main_seed = 2009
serial = "serial_20230127T161146"

[range_estimation.experimental]
num_mc_runs = 100
num_restarts = 20
num_samples = 512
num_trials = 200
num_warmup = 10
q = 5
root = "Data"
main_seed = 2009
serial = "serial_20230127T161146"

[localization.simulation]
num_mc_runs = 100
num_restarts = 20
num_samples = 512
num_grid_trials = [
    20,
    40,
]
num_trials = 200
num_warmup = 20
q = 5
root = "Data"
main_seed = 2009
serial = "serial_20230127T161146"

[localization.experimental]
num_mc_runs = 100
num_restarts = 20
num_samples = 512
num_grid_trials = [
    20,
    40,
]
num_trials = 200
num_warmup = 20
q = 5
root = "Data"
main_seed = 2009
serial = "serial_20230127T161146"
