[range_estimation]
NUM_MC_RUNS = 100
NUM_RESTARTS = 20
NUM_SAMPLES = 512
NUM_TRIALS = 200
NUM_WARMUP = 10
Q = 5
ROOT = "Data"
SEED = 2009
SERIAL = "serial_20230125T225457"

[localization]
NUM_MC_RUNS = 100
NUM_RESTARTS = 40
NUM_SAMPLES = 1024
NUM_TRIALS = 500
NUM_WARMUP = 20
Q = 5
ROOT = "Data"
SEED = 2009
SERIAL = "serial_20230125T225457"
